### ISSUE TITLE
Stable diffusion Repo id must be in the form 'repo_name' or 'namespace/repo_name'

### ISSUE THREAD

**Issue by qihanlong** [mist-project/mist-v2#10]
Since my GPU isn't supported, I tried the CPU command and got a an error when trying to download from the stable diffusion repo:

```
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
12/17/2023 17:59:16 - INFO - __main__ - Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cpu
Mixed precision type: bf16

==precision: torch.float32==
Traceback (most recent call last):
  File "...\mist-v2\attacks\mist.py", line 1155, in <module>
    main(args)
  File "...\mist-v2\attacks\mist.py", line 898, in main
    pipeline = DiffusionPipeline.from_pretrained(
  File "...\miniconda3\envs\mist-v2\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 857, in from_pretrained
    cached_folder = cls.download(
  File "...\miniconda3\envs\mist-v2\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1178, in download
    config_file = hf_hub_download(
  File "...\miniconda3\envs\mist-v2\lib\site-packages\huggingface_hub\utils\_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)
  File "...\miniconda3\envs\mist-v2\lib\site-packages\huggingface_hub\utils\_validators.py", line 158, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': './stable-diffusion/stable-diffusion-1-5'. Use `repo_type` argument if needed.
Traceback (most recent call last):
  File "...\miniconda3\envs\mist-v2\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "...\miniconda3\envs\mist-v2\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "...\miniconda3\envs\mist-v2\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "...\miniconda3\envs\mist-v2\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "...\miniconda3\envs\mist-v2\lib\site-packages\accelerate\commands\launch.py", line 986, in launch_command
    simple_launcher(args)
  File "...\miniconda3\envs\mist-v2\lib\site-packages\accelerate\commands\launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['...\\miniconda3\\envs\\mist-v2\\python.exe', 'attacks/mist.py', '--low_vram_mode', '--instance_data_dir', 'original', '--output_dir', 'output/', '--class_data_dir', 'data/class', '--instance_prompt', 'an illustration of a stone statue, high quality, masterpiece', '--class_prompt', 'an illustration of a stone statue, high quality, masterpiece', '--mixed_precision', 'bf16']' returned non-zero exit status 1.
```
I tried changing the `--pretrained_model_name_or_path` flag to `runwayml/stable-diffusion-1-5`, but got an authorization error:
```
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/runwayml/stable-diffusion-1-5/resolve/main/model_index.json
```

**Comment by caradryanl** [comment]
We currently do not support directly loading model from huggingface. You can download SD1-5 from our given Google Driven link, as detailed in our README.
