### ISSUE TITLE
程序运行时出现以下问题，如何解决？？

### ISSUE THREAD

**Issue by JaylenMeng** [mist-project/mist-v2#12]
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "E:\Mist_v2\Mist启动器\Mist启动器\mist-v2\venv\lib\site-packages\gradio\queueing.py", line 459, in call_prediction
    output = await route_utils.call_process_api(
  File "E:\Mist_v2\Mist启动器\Mist启动器\mist-v2\venv\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "E:\Mist_v2\Mist启动器\Mist启动器\mist-v2\venv\lib\site-packages\gradio\blocks.py", line 1533, in process_api
    result = await self.call_function(
  File "E:\Mist_v2\Mist启动器\Mist启动器\mist-v2\venv\lib\site-packages\gradio\blocks.py", line 1151, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\Mist_v2\Mist启动器\Mist启动器\mist-v2\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\Mist_v2\Mist启动器\Mist启动器\mist-v2\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "E:\Mist_v2\Mist启动器\Mist启动器\mist-v2\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\Mist_v2\Mist启动器\Mist启动器\mist-v2\venv\lib\site-packages\gradio\utils.py", line 678, in wrapper
    response = f(*args, **kwargs)
  File "E:\Mist_v2\Mist启动器\Mist启动器\mist-v2\src\mist-webui.py", line 20, in process_image
    main(args)
  File "E:\Mist_v2\Mist启动器\Mist启动器\mist-v2\src\attacks\mist.py", line 851, in main
    accelerator = Accelerator(
  File "E:\Mist_v2\Mist启动器\Mist启动器\mist-v2\venv\lib\site-packages\accelerate\accelerator.py", line 444, in __init__
    raise ValueError(err.format(mode="bf16", requirement="PyTorch >= 1.10 and a supported device."))
ValueError: bf16 mixed precision requires PyTorch >= 1.10 and a supported device.
Traceback (most recent call last):
  File "E:\Mist_v2\Mist启动器\Mist启动器\mist-v2\venv\lib\site-packages\gradio\queueing.py", line 459, in call_prediction
    output = await route_utils.call_process_api(
  File "E:\Mist_v2\Mist启动器\Mist启动器\mist-v2\venv\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "E:\Mist_v2\Mist启动器\Mist启动器\mist-v2\venv\lib\site-packages\gradio\blocks.py", line 1533, in process_api
    result = await self.call_function(
  File "E:\Mist_v2\Mist启动器\Mist启动器\mist-v2\venv\lib\site-packages\gradio\blocks.py", line 1151, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\Mist_v2\Mist启动器\Mist启动器\mist-v2\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\Mist_v2\Mist启动器\Mist启动器\mist-v2\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "E:\Mist_v2\Mist启动器\Mist启动器\mist-v2\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\Mist_v2\Mist启动器\Mist启动器\mist-v2\venv\lib\site-packages\gradio\utils.py", line 678, in wrapper
    response = f(*args, **kwargs)
  File "E:\Mist_v2\Mist启动器\Mist启动器\mist-v2\src\mist-webui.py", line 20, in process_image
    main(args)
  File "E:\Mist_v2\Mist启动器\Mist启动器\mist-v2\src\attacks\mist.py", line 851, in main
    accelerator = Accelerator(
  File "E:\Mist_v2\Mist启动器\Mist启动器\mist-v2\venv\lib\site-packages\accelerate\accelerator.py", line 444, in __init__
    raise ValueError(err.format(mode="bf16", requirement="PyTorch >= 1.10 and a supported device."))
ValueError: bf16 mixed precision requires PyTorch >= 1.10 and a supported device.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Mist_v2\Mist启动器\Mist启动器\mist-v2\venv\lib\site-packages\gradio\queueing.py", line 497, in process_events    response = await self.call_prediction(awake_events, batch)
  File "E:\Mist_v2\Mist启动器\Mist启动器\mist-v2\venv\lib\site-packages\gradio\queueing.py", line 468, in call_prediction
    raise Exception(str(error) if show_error else None) from error
Exception: None

**Comment by 1lch2** [comment]
另一个仓库里写了常见问题，可以参考下：https://github.com/mist-project/mist-v2-documentation-cn?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

**Comment by JaylenMeng** [comment]
> 另一个仓库里写了常见问题，可以参考下：https://github.com/mist-project/mist-v2-documentation-cn?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

我看了一下，并没有什么帮助，我的环境配置和环境测试都是OK的，至少启动器里没有出现问题。

**Comment by 1lch2** [comment]
> > 另一个仓库里写了常见问题，可以参考下：https://github.com/mist-project/mist-v2-documentation-cn?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98
> 
> 我看了一下，并没有什么帮助，我的环境配置和环境测试都是OK的，至少启动器里没有出现问题。

试试手动安装一下pytorch 1.10？

**Comment by caradryanl** [comment]
Problems about the boot version should be asked through Discord or QQ. 
关于启动器的问题请在QQ或者Discord提问
