### ISSUE TITLE
Dependencies error in provided colab notebook, with workarounds.

### ISSUE THREAD

**Issue by ghost** [mist-project/mist-v2#25]
### Summary
Several dependency errors found in the Colab notebook, which may cause a range of unexpected and unmentioned errors. To address this, I've came up with some workarounds.

This includes:

1. Downgrade several PIP packages (torch, nvidia stuff)
2. Installing missing package (jax)

### Workaround

Use this [shared Notebook](https://colab.research.google.com/drive/163cG_wA4MVYLSjkuduDFUTRnei0FWg7D?usp=drive_link)

### Why not open a PR to change the requirements.txt

Well, I would like to, but considering I run only once the notebook in google colab instead of on my home laboratory, I guess those problems is caused by some mysterious Google preinstalled packages, which might not lead to similar problems in local deployment. To avoid unnecessary downgrades, which should be always paid consideration to since there are performance and security concerns, I opened this issue to both propose a solution for those without GPUs but want to use Colab. 

### Another problem (might be my fault or temporary downtime)

The Gradio shared public link doesn't appear to work. Workaround: Used Google Colab builtin port forwarding.

Update: Gradio share link API is down now.

**Comment by caradryanl** [comment]
Thank you for mentioning this! The Colab problem is exactly caused by Google's updates of the preinstalled packages. I am trying to add an independent requirements.txt to fix this. But it may be on the shelf weeks later for I am busying with another work.

**Comment by Azleal** [comment]
> Thank you for mentioning this! The Colab problem is exactly caused by Google's updates of the preinstalled packages. I am trying to add an independent requirements.txt to fix this. But it may be on the shelf weeks later for I am busying with another work.

thank you for your time. I encountered issues with colab too. 
I followed the steps, everthing works fine before the 3rd step.
<img width="1548" alt="image" src="https://github.com/psyker-team/mist-v2/assets/7901126/57e48639-54ea-4bb8-aa41-3b15e5bae7cf">

here's detailed output:
```

!python mist-webui.py
2024-06-19 02:47:05.744521: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-06-19 02:47:05.744593: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-06-19 02:47:05.746306: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-06-19 02:47:05.754639: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-06-19 02:47:06.878517: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/content/mist-v2/mist-webui.py", line 2, in <module>
    from attacks.mist import main
  File "/content/mist-v2/attacks/mist.py", line 17, in <module>
    import diffusers
  File "/usr/local/lib/python3.10/dist-packages/diffusers/__init__.py", line 36, in <module>
    from .models import (
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/__init__.py", line 33, in <module>
    from .controlnet_flax import FlaxControlNetModel
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/controlnet_flax.py", line 25, in <module>
    from .modeling_flax_utils import FlaxModelMixin
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/modeling_flax_utils.py", line 45, in <module>
    class FlaxModelMixin:
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/modeling_flax_utils.py", line 192, in FlaxModelMixin
    def init_weights(self, rng: jax.random.KeyArray) -> Dict:
  File "/usr/local/lib/python3.10/dist-packages/jax/_src/deprecations.py", line 54, in getattr
    raise AttributeError(f"module {module!r} has no attribute {name!r}")
AttributeError: module 'jax.random' has no attribute 'KeyArray'
```

please help me with this. THANKS

**Comment by ghost** [comment]
My apology. Currently Mist is unable to run on Google Colab because the massive count of conflicts between Colab preinstalled and dependency of Mist, and both of the two are constantly changing. Please wait for official maintainer to make improvements. And Google **does not** allow running WebUI-like non interactive notebooks any more. (I have got my Notebook shut down because of running such notebooks) Perhaps someone with time need to create a Interactive Notebook UI to meet google's standards. Or you have to pay for the service.

**Comment by caradryanl** [comment]
Yes, we have detected the problem and are now working on it by finding
other free resources. Before that maybe you should use it locally.
