### ISSUE TITLE
Google Colab Error 

### ISSUE THREAD

**Issue by Jimmynycu** [mist-project/mist-v2#28]
Seems there is unable to find stable diffusion files 
```
cp: cannot stat '/content/drive/MyDrive/Diffusers/stable-diffusion-1-5': No such file or directory
```
And also error in webui.py
```
Traceback (most recent call last):
  File "/content/mist-v2/mist-webui.py", line 2, in <module>
    from attacks.mist import main
  File "/content/mist-v2/attacks/mist.py", line 17, in <module>
    import diffusers
  File "/usr/local/lib/python3.10/dist-packages/diffusers/__init__.py", line 38, in <module>
    from .models import (
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/__init__.py", line 33, in <module>
    from .controlnet_flax import FlaxControlNetModel
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/controlnet_flax.py", line 25, in <module>
    from .modeling_flax_utils import FlaxModelMixin
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/modeling_flax_utils.py", line 45, in <module>
    class FlaxModelMixin:
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/modeling_flax_utils.py", line 194, in FlaxModelMixin
    def init_weights(self, rng: jax.random.KeyArray) -> Dict:
  File "/usr/local/lib/python3.10/dist-packages/jax/_src/deprecations.py", line 55, in getattr
    raise AttributeError(f"module {module!r} has no attribute {name!r}")
AttributeError: module 'jax.random' has no attribute 'KeyArray'
```
Is there missing instruction that user should download stable diffusion and setup the pipline by themselves?

**Comment by caradryanl** [comment]
Currently Colab is not usable due to Google's restriction. I feel sorry for that
